apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: {{ printf "%s-%s" .Release.Name .Chart.Name }}