# we create namespace to isolate services and create policies and limit resources within each namespace
# all the resouces in the names can communicate with each other with just their name but talk to other namespace
  # "db-service.dev.svc.cluster.local" service-name.namespace.service.domain
# all the resources are created in default namespace if --namespace arg is not used

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dev

# we can use namespace to limit quota
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-quota
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limit.cpu: "10"
    limit.memory: 10Gi