# schedule job
# there will be 3 specs section becareful
# cron expressions: 
# * * * * * 

# 1: minutes (0-59)                  Allow special: , - * /
# 2: hours (0-23)                    Allow special: , - * /
# 3: day of the month (1-31)         Allow special: , - * ? / L W C
# 4: month (1-12)                    Allow special: , - * /
# 5: day of the week (0-6)           Allow special: , - * ? / L C #
# 6: year (empty or 1970-2099)       Allow special: , - * /

# 0 0 12 * * ?	                    Fire at 12:00 PM (noon) every day
# 0 15 10 ? * *	                    Fire at 10:15 AM every day
# 0 15 10 * * ?	                    Fire at 10:15 AM every day
# 0 15 10 * * ? *	                  Fire at 10:15 AM every day
# 0 15 10 * * ? 2005	              Fire at 10:15 AM every day during the year 2005
# 0 * 14 * * ?	                    Fire every minute starting at 2:00 PM and ending at 2:59 PM, every day
# 0 0/5 14 * * ?	                  Fire every 5 minutes starting at 2:00 PM and ending at 2:55 PM, every day
# 0 0/5 14,18 * * ?	                Fire every 5 minutes starting at 2:00 PM and ending at 2:55 PM, AND fire every 5 minutes starting at 6:00 PM and ending at 6:55 PM, every day
# 0 0-5 14 * * ?	                  Fire every minute starting at 2:00 PM and ending at 2:05 PM, every day
# 0 10,44 14 ? 3 WED	              Fire at 2:10 PM and at 2:44 PM every Wednesday in the month of March
# 0 15 10 ? * MON-FRI	              Fire at 10:15 AM every Monday, Tuesday, Wednesday, Thursday and Friday
# 0 15 10 15 * ?	                  Fire at 10:15 AM on the 15th day of every month
# 0 15 10 L * ?	                    Fire at 10:15 AM on the last day of every month
# 0 15 10 ? * 6L	                  Fire at 10:15 AM on the last Friday of every month
# 0 15 10 ? * 6L	                  Fire at 10:15 AM on the last Friday of every month
# 0 15 10 ? * 6L 2002-2005	        Fire at 10:15 AM on every last friday of every month during the years 2002, 2003, 2004, and 2005
# 0 15 10 ? * 6#3	                  Fire at 10:15 AM on the third Friday of every month
# 0 0 12 1/5 * ?	                  Fire at 12 PM (noon) every 5 days every month, starting on the first day of the month
# 0 11 11 11 11 ?	                  Fire every November 11 at 11:11 AM

# * = every tick (* in minutes meaning every minute)
# ? = indicates no specific value (? in 5th position meaning i dont care which day of the week it is, it will fire on 3th position)
  # 0 15 10 15 * ? Fire at 10:15 A.M. on the 15th day of every month
# - = range (10-12 hour field fires at every hour 10, 11, 12)
# , = separate multiple allowed values (“MON,WED,FRI”)
# / = A slash indicates increments (“0/15” in the seconds field means the seconds 0, 15, 30, and 45.)
  # ‘1/3’ in the day_of_month field means fire every 3 days starting on the first day of the month.
  # 0 0/5 14 * * ? Fire every 5 minutes starting at 2:00 P.M. and ending at 2:55 P.M., every day
# L = An uppercase L indicates last of the values. (“L” in the day_of_month field means the last day of the month. “L” in the week_of_day field means 7 or SAT.)
# W = An uppercase W indicates nearest weekday of the specified date. (“15W” as the value for the day_of_month field, it means the nearest weekday to the 15th of the month.)
  # If 15th is a Saturday, the trigger will fire on Friday the 14th.
  # If 15th is a Sunday, the trigger will fire on Monday the 16th.
  # If 15th is a Tuesday, it will fire on Tuesday the 15th. 
# # = A hash indicates the Nth day of the month (“6#3” in the day_of_week field means “the third Friday of the month.”)

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      completion: 3
      parallelism: 3
      template:
        spec: 
          containers:
            - name: reporting-tool
              image: reporting-tool
          restartPolicy: never
