
apiVersion: batch/v1
kind: Job
metadata: 
  name: math-add-job
specs:
  completions: 3 # this will create 3 pods that runs the math expressions jobs will have 3 desired counts
  parallesim: 3 # default job is created sequentially
  template:
    specs:
      containers:
      - name: math-add
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never/OnFailure

# if during job creation for multiple pods, one of the pod fails, job will create as many pods required to ensure 3(completions) pods are created