# a centralized location to create a volume that can be shared with multiple pods
# a persistent volume
  # is cluster wide pool configure by admin
  # user can select storage from this pool using persistent volume claims

#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec: 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4

# modes ReadOnlyMany, ReadWriteOnce or ReadWriteMany mode.