# store sensitive data
# store in encoded or hashed format

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: mysql 
  DB_User: root
  DB_Password: cGFzd3Jk

# we need to encode the password:  The data that you encode may contain many unrecognized characters, line feeds, etc., so it is convenient to encode them.
# echo –n ‘mysql’ | base64